version: '3.9'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  log-ingestion-service:
    build:
      context: ..
      dockerfile: log-ingestion-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_REPLICATION_FACTOR: 1        # increase to 3 on a multi-broker cluster
      RATE_LIMIT_RPS: 1000
    depends_on:
      - kafka

  anomaly-detector-service:
    build:
      context: ..
      dockerfile: anomaly-detector-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_REPLICATION_FACTOR: 1        # increase to 3 on a multi-broker cluster
      KAFKA_MAX_POLL_RECORDS: 100
      DETECTOR_WINDOW_SIZE: 30
      DETECTOR_SIGNAL_WINDOW_SIZE: 10
      DETECTOR_Z_SCORE_THRESHOLD: 2.0
    depends_on:
      - kafka

  alert-service:
    build:
      context: ..
      dockerfile: alert-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - kafka
