apiVersion: v1
kind: Service
metadata:
  name: log-ingestion-service
  namespace: log-pipeline
spec:
  selector:
    app: log-ingestion-service
  type: NodePort       # Exposes port 8080 on your localhost so you can POST logs from outside the cluster
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # curl http://localhost:30080/api/v1/logs
